import type { GrammarConcept } from "./knowledge";

export const EXTRA_CONCEPTS: GrammarConcept[] = [
  {
    id: "to_be_contractions",
    name: "Verbo TO BE en forma corta (I'm, you're, it's)",
    level: "A1",
    pattern: "SUBJECT + TO BE → SHORT FORM",
    rules: ["I am → I'm / You are → you're / He is → he's", "We are → we're / They are → they're", "En conversación siempre se usan las formas cortas"],
    prerequisites: ["to_be"],
    functions: ["introduce_myself", "describe_people_objects"],
    common_errors: [
      { wrong: "I am happy but I am tired", right: "I'm happy but I'm tired", why: "Usa formas cortas al hablar: suena natural" },
      { wrong: "Its raining", right: "It's raining", why: "it's = it is (con apóstrofo)" },
    ],
    examples: [
      { en: "I'm from Chile.", pr: "aim from chile", es: "Soy de Chile." },
      { en: "She's my best friend.", pr: "shis mai best frend", es: "Ella es mi mejor amiga." },
    ],
    produce: { question_es: "Preséntate usando formas cortas.", answer_en: "I'm a developer and I'm from Chile.", answer_pr: "aim a developa" },
    skills: ["grammar", "speaking", "fluency"],
  },
  {
    id: "possessive_basic",
    name: "Possessivos básicos + TO BE interrogativo (my, your, his, her)",
    level: "A1",
    pattern: "TO BE + SUBJECT + … ? · POSSESSIVE + NOUN",
    rules: ["my (mi), your (tu), his (su de él), her (su de ella)", "Pregunta con to be: Is he…? Is she…?", "his/her concuerdan con el dueño, no con la cosa"],
    prerequisites: ["to_be"],
    functions: ["introduce_myself", "describe_people_objects"],
    common_errors: [
      { wrong: "She name is Ana", right: "Her name is Ana", why: "Dueña femenina → her" },
      { wrong: "What is you name?", right: "What is your name?", why: "Antes de un nombre se usa your" },
    ],
    examples: [
      { en: "His name is Pedro.", pr: "jis neim is pedro", es: "Su nombre (de él) es Pedro." },
      { en: "What is your name?", pr: "uat is ior neim", es: "¿Cómo te llamas?" },
    ],
    produce: { question_es: "Pregúntale a alguien su nombre y presenta a un amigo.", answer_en: "What is your name? His name is…", answer_pr: "uat is ior neim" },
    skills: ["grammar", "speaking"],
  },
  {
    id: "wh_to_be",
    name: "WH-Questions con TO BE (What / Where + to be)",
    level: "A1",
    pattern: "WHAT/WHERE + TO BE + SUBJECT",
    rules: ["Con to be NO se usa do: Where are you?", "What is your job?", "Orden: Where + is + subject"],
    prerequisites: ["to_be"],
    functions: ["ask_basic_questions", "interview_basics"],
    common_errors: [
      { wrong: "Where you are?", right: "Where are you?", why: "En pregunta el verbo va antes del sujeto" },
      { wrong: "What is you doing?", right: "What are you doing?", why: "Con you se usa are" },
    ],
    examples: [
      { en: "Where are you from?", pr: "uer ar iu from", es: "¿De dónde eres?" },
      { en: "What is your job?", pr: "uat is ior yob", es: "¿Cuál es tu trabajo?" },
    ],
    produce: { question_es: "Pregunta dónde vive tu tutor y qué es su trabajo.", answer_en: "Where are you from? What is your job?", answer_pr: "uer ar iu from" },
    skills: ["grammar", "speaking", "response_time"],
  },
  {
    id: "why_because",
    name: "WHY y BECAUSE + TO BE (preguntar y responder por qué)",
    level: "A1",
    pattern: "WHY + TO BE + SUBJECT ? · BECAUSE + SUBJECT + TO BE",
    rules: ["why (por qué) hace la pregunta", "because (porque) da la respuesta", "Responder: Because I am tired."],
    prerequisites: ["to_be", "wh_to_be"],
    functions: ["ask_basic_questions", "talk_about_now"],
    common_errors: [
      { wrong: "Because of I am tired", right: "Because I am tired", why: "because + frase completa" },
      { wrong: "Why you are happy?", right: "Why are you happy?", why: "Orden: why + are + subject" },
    ],
    examples: [
      { en: "Why are you sad?", pr: "uai ar iu sad", es: "¿Por qué estás triste?" },
      { en: "I am happy because I passed the test.", pr: "ai am japi bikaus ai past de test", es: "Estoy feliz porque aprobé el examen." },
    ],
    produce: { question_es: "Pregunta por qué está contento tu tutor.", answer_en: "Why are you happy? Because I am learning English.", answer_pr: "uai ar iu japi" },
    skills: ["grammar", "speaking", "response_time"],
  },
  {
    id: "a_an",
    name: "A vs AN (artículos indefinidos)",
    level: "A1",
    pattern: "A/AN + NOUN",
    rules: ["a + consonante (a dog)", "an + vocal sonora (an apple, an engineer)", "a/an solo con singulares: I am an engineer"],
    prerequisites: ["to_be"],
    functions: ["describe_people_objects"],
    common_errors: [
      { wrong: "I am an software engineer", right: "I am a software engineer", why: "Antes de consonante → a" },
      { wrong: "a apple", right: "an apple", why: "Antes de vocal sonora → an" },
    ],
    examples: [
      { en: "I am an engineer.", pr: "ai am an enguinir", es: "Soy ingeniero." },
      { en: "It is a big city.", pr: "it is a big siti", es: "Es una ciudad grande." },
    ],
    produce: { question_es: "Di tu profesión con el artículo correcto.", answer_en: "I am a developer.", answer_pr: "ai am a developa" },
    skills: ["grammar", "vocabulary"],
  },
  {
    id: "adjectives_qualifiers",
    name: "Adjetivos calificativos (big, small, nice…)",
    level: "A1",
    pattern: "TO BE + ADJECTIVE · ADJECTIVE + NOUN",
    rules: ["Van antes del sustantivo: a nice house", "Con to be: the house is nice", "No cambian en plural: they are nice"],
    prerequisites: ["to_be", "a_an"],
    functions: ["describe_people_objects", "describe_location"],
    common_errors: [
      { wrong: "a house nice", right: "a nice house", why: "El adjetivo va antes del sustantivo" },
      { wrong: "The house is nices", right: "The house is nice", why: "Los adjetivos no llevan -s en plural" },
    ],
    examples: [
      { en: "It is a big house.", pr: "it is a big jaus", es: "Es una casa grande." },
      { en: "She is very kind.", pr: "shi is beri kaind", es: "Ella es muy amable." },
    ],
    produce: { question_es: "Describe tu casa o tu ciudad con 2 adjetivos.", answer_en: "My city is big and beautiful.", answer_pr: "mai siti is big and biutiful" },
    skills: ["vocabulary", "speaking"],
  },
  {
    id: "how_many_how_much",
    name: "HOW MANY / HOW MUCH (cantidades)",
    level: "A1",
    pattern: "HOW MANY + PLURAL ? · HOW MUCH + UNCOUNTABLE ?",
    rules: ["how many + cosas contables (apples)", "how much + cosas no contables (water, money)", "Respuesta: There are… / a lot / a little"],
    prerequisites: ["there_is_are"],
    functions: ["ask_basic_questions", "describe_location"],
    common_errors: [
      { wrong: "How much apples?", right: "How many apples?", why: "Manzanas son contables → many" },
      { wrong: "How many water?", right: "How much water?", why: "Agua no es contable → much" },
    ],
    examples: [
      { en: "How many rooms are there?", pr: "jau meni rums ar der", es: "¿Cuántas habitaciones hay?" },
      { en: "How much is it?", pr: "jau mach is it", es: "¿Cuánto cuesta?" },
    ],
    produce: { question_es: "Pregunta cuántas habitaciones hay en casa de tu tutor.", answer_en: "How many rooms are there? There are three.", answer_pr: "jau meni rums ar der" },
    skills: ["grammar", "vocabulary", "speaking"],
  },
  {
    id: "this_that_these_those",
    name: "THIS / THAT / THESE / THOSE + TO BE",
    level: "A1",
    pattern: "THIS/THAT + IS + NOUN · THESE/THOSE + ARE + NOUN",
    rules: ["this (esto/a, cerca) / that (eso/a, lejos)", "these (estos, cerca) / those (esos, lejos)", "this/that + is · these/those + are"],
    prerequisites: ["to_be"],
    functions: ["describe_people_objects", "describe_location"],
    common_errors: [
      { wrong: "These is my keys", right: "These are my keys", why: "these (plural) → are" },
      { wrong: "This are my books", right: "These are my books", why: "this es singular → these para plural" },
    ],
    examples: [
      { en: "This is my laptop.", pr: "dis is mai laptop", es: "Esta es mi laptop." },
      { en: "Those are my friends.", pr: "dous ar mai frends", es: "Aquellos son mis amigos." },
    ],
    produce: { question_es: "Señala cosas cerca y lejos de ti.", answer_en: "This is my phone and those are my keys.", answer_pr: "dis is mai foun" },
    skills: ["grammar", "vocabulary", "speaking"],
  },
  {
    id: "demonstrative_interrogative",
    name: "Demostrativos interrogativos (Is this…? Are those…?)",
    level: "A1",
    pattern: "IS/ARE + THIS/THAT/THESE/THOSE + … ?",
    rules: ["Is this your pen? (singular)", "Are those your keys? (plural)", "Responder: Yes, it is / No, they aren't"],
    prerequisites: ["this_that_these_those"],
    functions: ["ask_basic_questions"],
    common_errors: [
      { wrong: "Is this your keys?", right: "Are these your keys?", why: "keys es plural → are + these" },
      { wrong: "These is your pen?", right: "Is this your pen?", why: "Singular → is + this" },
    ],
    examples: [
      { en: "Is this your phone?", pr: "is dis ior foun", es: "¿Es tuyo este teléfono?" },
      { en: "Are those your friends?", pr: "ar dous ior frends", es: "¿Esos son tus amigos?" },
    ],
    produce: { question_es: "Pregunta si un objeto es de tu tutor.", answer_en: "Is this your laptop?", answer_pr: "is dis ior laptop" },
    skills: ["grammar", "speaking"],
  },
  {
    id: "present_simple_aux",
    name: "Present Simple: S, ES, IES + auxiliares DO/DOES",
    level: "A1",
    pattern: "SUBJECT + VERB(-S/-ES/-IES) · DO/DOES + SUBJECT + VERB ?",
    rules: ["he/she/it → -s; -es tras s, x, ch, sh, o; -ies tras consonante+y", "Pregunta con does: Does she work? (verbo en base)", "Negación: don't / doesn't + verbo en base"],
    prerequisites: ["present_simple"],
    functions: ["talk_about_routines", "ask_basic_questions"],
    common_errors: [
      { wrong: "He studyes", right: "He studies", why: "consonante + y → -ies" },
      { wrong: "Does she works?", right: "Does she work?", why: "Con does el verbo va en base" },
    ],
    examples: [
      { en: "She works from Monday to Friday.", pr: "shi uorks from monday tu fraidei", es: "Ella trabaja de lunes a viernes." },
      { en: "Does he speak Spanish?", pr: "das ji spik spanish", es: "¿Él habla español?" },
    ],
    produce: { question_es: "Pregunta qué hace tu compañero en el trabajo.", answer_en: "Does he work on weekends? No, he doesn't.", answer_pr: "das ji uork on uikends" },
    skills: ["grammar", "speaking", "writing"],
  },
  {
    id: "how_often",
    name: "HOW OFTEN + DO/DOES (¿con qué frecuencia?)",
    level: "A1",
    pattern: "HOW OFTEN + DO/DOES + SUBJECT + VERB ?",
    rules: ["how often pregunta frecuencia", "Respuestas: once a week, twice a month", "Pregunta: How often do you exercise?"],
    prerequisites: ["frequency_adverbs", "present_simple"],
    functions: ["talk_about_routines", "ask_basic_questions"],
    common_errors: [
      { wrong: "How often you exercise?", right: "How often do you exercise?", why: "Necesita auxiliar do" },
      { wrong: "I exercise one time by week", right: "I exercise once a week", why: "once a week / twice a month" },
    ],
    examples: [
      { en: "How often do you go to the gym?", pr: "jau ofen du iu gou tu de yim", es: "¿Con qué frecuencia vas al gimnasio?" },
      { en: "I go twice a week.", pr: "ai gou tuais a uik", es: "Voy dos veces por semana." },
    ],
    produce: { question_es: "Pregunta a tu tutor con qué frecuencia hace algo.", answer_en: "How often do you travel? I travel once a year.", answer_pr: "jau ofen du iu travel" },
    skills: ["grammar", "speaking", "fluency"],
  },
  {
    id: "adjectives_vs_adverbs",
    name: "Adjetivos vs Adverbios (quick / quickly)",
    level: "A2",
    pattern: "ADJECTIVE + NOUN · VERB + ADVERB",
    rules: ["Adjetivo describe un nombre: a quick answer", "Adverbio describe un verbo: answer quickly", "Regla: adjetivo + -ly = adverbio (careful → carefully)"],
    prerequisites: ["adjectives_qualifiers", "present_simple"],
    functions: ["describe_people_objects"],
    common_errors: [
      { wrong: "She speaks English good", right: "She speaks English well", why: "well es adverbio irregular de good" },
      { wrong: "He runs very quick", right: "He runs very quickly", why: "Describe el verbo → adverbio (-ly)" },
    ],
    examples: [
      { en: "She is a fast driver.", pr: "shi is a fast draiva", es: "Ella es una conductora rápida." },
      { en: "He speaks English well.", pr: "ji spiks inglish uel", es: "Él habla inglés bien." },
    ],
    produce: { question_es: "Di cómo trabaja alguien (adverbio).", answer_en: "She works hard and quickly.", answer_pr: "shi uorks jard and kuikli" },
    skills: ["grammar", "vocabulary"],
  },
  {
    id: "intensifiers",
    name: "Intensificadores (very, really, quite, too)",
    level: "A2",
    pattern: "INTENSIFIER + ADJECTIVE/ADVERB",
    rules: ["very (muy) / really (realmente) / quite (bastante) / too (demasiado)", "Van antes del adjetivo: very tired", "too = demasiado (con sentido negativo)"],
    prerequisites: ["adjectives_qualifiers"],
    functions: ["describe_people_objects", "express_needs_help"],
    common_errors: [
      { wrong: "I am very much tired", right: "I am very tired", why: "very + adjetivo (sin much)" },
      { wrong: "The movie was too good para elogiar", right: "The movie was really good", why: "too = excesivo; usa very/really para elogiar" },
    ],
    examples: [
      { en: "The class is really interesting.", pr: "de klas is rili interes-ting", es: "La clase es realmente interesante." },
      { en: "This bag is too heavy.", pr: "dis bag is tu jevi", es: "Esta bolsa es demasiado pesada." },
    ],
    produce: { question_es: "Da tu opinión con un intensificador.", answer_en: "The course is very useful.", answer_pr: "de kors is beri iusful" },
    skills: ["vocabulary", "speaking"],
  },
  {
    id: "look_see_watch",
    name: "LOOK / SEE / WATCH",
    level: "A2",
    pattern: "LOOK AT + OBJECT · SEE + OBJECT · WATCH + OBJECT",
    rules: ["look at = mirar fijamente algo", "see = ver (sin esfuerzo, por casualidad)", "watch = ver con atención (TV, un partido)"],
    prerequisites: ["present_simple"],
    functions: ["describe_people_objects", "talk_about_routines"],
    common_errors: [
      { wrong: "I watch a bird in the sky", right: "I see a bird in the sky", why: "Ver por casualidad → see" },
      { wrong: "Look the board", right: "Look at the board", why: "look necesita 'at' antes del objeto" },
    ],
    examples: [
      { en: "I watch TV every night.", pr: "ai uoch ti-vi evri nait", es: "Veo TV todas las noches." },
      { en: "Look at that car!", pr: "luk at dat kar", es: "¡Mira ese auto!" },
    ],
    produce: { question_es: "Cuenta qué viste y qué miras seguido.", answer_en: "I saw a friend and I watch a movie later.", answer_pr: "ai so a frend" },
    skills: ["vocabulary", "speaking"],
  },
  {
    id: "modal_intro",
    name: "Verbos modales: qué son (can, could, should, would, must)",
    level: "A2",
    pattern: "MODAL + BASE VERB",
    rules: ["Los modales van seguidos del verbo en base, sin 'to'", "Son iguales para todas las personas (he can, she should)", "No llevan do/does ni -s"],
    prerequisites: ["can_ability"],
    functions: ["express_needs_help", "interview_basics"],
    common_errors: [
      { wrong: "He shoulds study", right: "He should study", why: "Los modales no llevan -s" },
      { wrong: "I must to go", right: "I must go", why: "Modal + verbo en base, sin 'to'" },
    ],
    examples: [
      { en: "You should rest.", pr: "iu shud rest", es: "Deberías descansar." },
      { en: "We must arrive on time.", pr: "ui mast araiv on taim", es: "Debemos llegar a tiempo." },
    ],
    produce: { question_es: "Da un consejo y di una obligación.", answer_en: "You should sleep more. I must finish this.", answer_pr: "iu shud slip mor" },
    skills: ["grammar", "speaking"],
  },
  {
    id: "should",
    name: "Verbo modal SHOULD (deberías)",
    level: "A2",
    pattern: "SUBJECT + SHOULD + BASE VERB",
    rules: ["should = consejo u opinión (deberías)", "Negación: shouldn't", "Pregunta: Should I…?"],
    prerequisites: ["modal_intro"],
    functions: ["express_needs_help", "handle_work_situations"],
    common_errors: [
      { wrong: "You should to rest", right: "You should rest", why: "should + verbo en base, sin 'to'" },
      { wrong: "You shoulds call him", right: "You should call him", why: "should no lleva -s" },
    ],
    examples: [
      { en: "You should drink more water.", pr: "iu shud drink mor uata", es: "Deberías tomar más agua." },
      { en: "Should I bring my laptop?", pr: "shud ai bring mai laptop", es: "¿Debería llevar mi laptop?" },
    ],
    produce: { question_es: "Da un consejo a tu tutor.", answer_en: "You should take a break.", answer_pr: "iu shud teik a breik" },
    skills: ["grammar", "speaking"],
  },
  {
    id: "object_pronouns",
    name: "Pronombres objeto (me, you, him, her, us, them)",
    level: "A2",
    pattern: "VERB + OBJECT PRONOUN",
    rules: ["me, you, him, her, it, us, them", "Van tras el verbo o preposición: help me, with her", "Cambian según el objeto, no el sujeto"],
    prerequisites: ["possessive_basic", "present_simple"],
    functions: ["interview_basics", "describe_people_objects"],
    common_errors: [
      { wrong: "I see she", right: "I see her", why: "Tras el verbo se usa her (objeto)" },
      { wrong: "Call he tomorrow", right: "Call him tomorrow", why: "him es el pronombre objeto" },
    ],
    examples: [
      { en: "Please call me later.", pr: "plis kol mi leita", es: "Por favor, llámame luego." },
      { en: "I work with them.", pr: "ai uork uit dem", es: "Trabajo con ellos." },
    ],
    produce: { question_es: "Dime a quién ayudas en tu trabajo.", answer_en: "I help them every day.", answer_pr: "ai jelp dem evri dei" },
    skills: ["grammar", "speaking"],
  },
  {
    id: "would_like",
    name: "WOULD LIKE (me gustaría)",
    level: "A2",
    pattern: "SUBJECT + WOULD LIKE + NOUN/INFINITIVE",
    rules: ["would like = querer de forma educada", "+ sustantivo: I'd like a coffee", "+ verbo: I'd like to learn English"],
    prerequisites: ["modal_intro"],
    functions: ["handle_work_situations", "express_needs_help"],
    common_errors: [
      { wrong: "I would like drink coffee", right: "I would like to drink coffee", why: "Tras would like el verbo lleva 'to'" },
      { wrong: "Would you like something drink?", right: "Would you like something to drink?", why: "to drink al final" },
    ],
    examples: [
      { en: "I'd like to improve my English.", pr: "aid laik tu impruv mai inglish", es: "Me gustaría mejorar mi inglés." },
      { en: "Would you like some tea?", pr: "ud iu laik sam ti", es: "¿Te gustaría un té?" },
    ],
    produce: { question_es: "Ofrécele algo a tu tutor y acepta con cortesía.", answer_en: "Would you like some coffee? Yes, I'd like that.", answer_pr: "ud iu laik sam kofi" },
    skills: ["grammar", "speaking", "fluency"],
  },
  {
    id: "possessive_adjectives",
    name: "Pronombres posesivos (mine, yours, his, hers)",
    level: "A2",
    pattern: "POSSESSIVE PRONOUN (sin sustantivo)",
    rules: ["mine (mío), yours (tuyo), his, hers, ours, theirs", "Reemplazan al sustantivo: It's mine", "Distinguir de my/your: This is my car → This car is mine"],
    prerequisites: ["possessive_basic", "object_pronouns"],
    functions: ["describe_people_objects"],
    common_errors: [
      { wrong: "This is my", right: "This is mine", why: "Sin sustantivo después → mine" },
      { wrong: "The book is her", right: "The book is hers", why: "En predicado se usa hers" },
    ],
    examples: [
      { en: "This laptop is mine.", pr: "dis laptop is main", es: "Esta laptop es mía." },
      { en: "That idea was yours.", pr: "dat aidia uos iors", es: "Esa idea fue tuya." },
    ],
    produce: { question_es: "Dime de quién es un objeto tuyo.", answer_en: "This phone is mine.", answer_pr: "dis foun is main" },
    skills: ["grammar", "vocabulary"],
  },
  {
    id: "what_vs_which",
    name: "WHAT vs WHICH (qué vs cuál)",
    level: "A2",
    pattern: "WHAT + … ? · WHICH + NOUN/ONE + … ?",
    rules: ["what = abierto (sin opciones): What do you want?", "which = elegir entre opciones: Which color do you prefer?", "which + one/ones: Which one is yours?"],
    prerequisites: ["wh_questions", "present_simple"],
    functions: ["ask_basic_questions", "interview_basics"],
    common_errors: [
      { wrong: "What one do you prefer?", right: "Which one do you prefer?", why: "Al elegir entre opciones → which" },
      { wrong: "Which is your job?", right: "What is your job?", why: "Pregunta abierta → what" },
    ],
    examples: [
      { en: "What do you need?", pr: "uat du iu nid", es: "¿Qué necesitas?" },
      { en: "Which shirt is cheaper?", pr: "uich shart is chipa", es: "¿Cuál camisa es más barata?" },
    ],
    produce: { question_es: "Pregunta entre dos opciones concretas.", answer_en: "Which one do you like more, tea or coffee?", answer_pr: "uich uan du iu laik mor" },
    skills: ["grammar", "vocabulary"],
  },
  {
    id: "could",
    name: "COULD (pasado de can / petición cortés)",
    level: "A2",
    pattern: "SUBJECT + COULD + BASE VERB",
    rules: ["could = habilidad en pasado (I could swim)", "could = petición cortés (Could you help me?)", "Nunca: coulds o could to"],
    prerequisites: ["can_ability", "modal_intro"],
    functions: ["handle_work_situations", "express_needs_help"],
    common_errors: [
      { wrong: "Could you to open the door?", right: "Could you open the door?", why: "could + verbo en base, sin 'to'" },
      { wrong: "I can swim when I was five (ya no)", right: "I couldn't swim when I was five", why: "Pasado → couldn't" },
    ],
    examples: [
      { en: "Could you repeat that, please?", pr: "kud iu ripit dat plis", es: "¿Podrías repetir eso, por favor?" },
      { en: "When I was six I could read.", pr: "uen ai uos six ai kud rid", es: "Cuando tenía seis años sabía leer." },
    ],
    produce: { question_es: "Pide algo con cortesía usando could.", answer_en: "Could you help me with this?", answer_pr: "kud iu jelp mi uit dis" },
    skills: ["grammar", "speaking", "fluency"],
  },
  {
    id: "either_neither",
    name: "EITHER / NEITHER y EITHER… OR",
    level: "A2",
    pattern: "EITHER … OR · NEITHER … NOR",
    rules: ["either…or = o…o (opciones)", "neither…nor = ni…ni (negación)", "neither/neither of + plural: neither of them"],
    prerequisites: ["object_pronouns"],
    functions: ["ask_basic_questions", "handle_work_situations"],
    common_errors: [
      { wrong: "I don't like neither", right: "I don't like either", why: "Con negación se usa either" },
      { wrong: "Neither me or him", right: "Neither me nor him", why: "either va con or, neither con nor" },
    ],
    examples: [
      { en: "You can have either tea or coffee.", pr: "iu kan jav iter ti or kofi", es: "Puedes tomar té o café." },
      { en: "Neither option is good.", pr: "naider opshon is gud", es: "Ninguna opción es buena." },
    ],
    produce: { question_es: "Ofrece dos opciones y dile a tu tutor que puede elegir.", answer_en: "You can pick either tea or coffee.", answer_pr: "iu kan pik iter ti or kofi" },
    skills: ["grammar", "vocabulary"],
  },
  {
    id: "linking",
    name: "Palabras de conexión (and, but, so, because)",
    level: "A2",
    pattern: "CLAUSE + CONNECTOR + CLAUSE",
    rules: ["and (y) / but (pero) / so (así que) / because (porque)", "Conectan dos ideas en una oración", "so da consecuencia; because da causa"],
    prerequisites: ["present_simple", "why_because"],
    functions: ["talk_about_routines", "interview_basics"],
    common_errors: [
      { wrong: "I was tired, but I went to sleep (no hay contraste)", right: "I was tired, so I went to sleep", why: "so expresa consecuencia" },
      { wrong: "I like coffee but I like tea", right: "I like coffee and I like tea", why: "but es para contraste" },
    ],
    examples: [
      { en: "I work hard but I enjoy it.", pr: "ai uork jard bat ai enyoi it", es: "Trabajo duro pero me gusta." },
      { en: "It was late, so we left.", pr: "it uos leit so ui left", es: "Era tarde, así que nos fuimos." },
    ],
    produce: { question_es: "Cuenta dos ideas unidas con so o but.", answer_en: "I was busy, so I stayed home.", answer_pr: "ai uos bisi so ai steid jom" },
    skills: ["grammar", "fluency", "writing"],
  },
  {
    id: "past_to_be",
    name: "Pasado de TO BE (was / were)",
    level: "A2",
    pattern: "SUBJECT + WAS/WERE + …",
    rules: ["was: I, he, she, it · were: you, we, they", "Negación: wasn't / weren't", "Pregunta: Was she…? Were you…?"],
    prerequisites: ["to_be", "past_simple"],
    functions: ["talk_about_past", "interview_basics"],
    common_errors: [
      { wrong: "You was late", right: "You were late", why: "con you se usa were" },
      { wrong: "I were happy", right: "I was happy", why: "con I se usa was" },
    ],
    examples: [
      { en: "I was at home yesterday.", pr: "ai uos at jom yestadei", es: "Estuve en casa ayer." },
      { en: "Were you tired?", pr: "uer iu taiad", es: "¿Estabas cansado?" },
    ],
    produce: { question_es: "Cuenta dónde estabas ayer.", answer_en: "I was at the office yesterday.", answer_pr: "ai uos at de ofis yestadei" },
    skills: ["grammar", "speaking"],
  },
  {
    id: "past_continuous",
    name: "Pasado continuo (was/were + -ing)",
    level: "A2",
    pattern: "SUBJECT + WAS/WERE + VERB-ING",
    rules: ["Acción en curso en el pasado", "was/were + verbo -ing: I was working", "Se usa con when: I was sleeping when you called"],
    prerequisites: ["present_continuous", "past_to_be"],
    functions: ["talk_about_past"],
    common_errors: [
      { wrong: "I was work when you called", right: "I was working when you called", why: "was + verbo -ing" },
      { wrong: "I was study all day", right: "I was studying all day", why: "Necesita verbo -ing" },
    ],
    examples: [
      { en: "I was watching TV at 9.", pr: "ai uos uoching ti-vi at nain", es: "Estaba viendo TV a las 9." },
      { en: "She was cooking when I arrived.", pr: "shi uos kuking uen ai araivd", es: "Ella cocinaba cuando llegué." },
    ],
    produce: { question_es: "Cuenta qué hacías cuando sonó el teléfono.", answer_en: "I was working when you called.", answer_pr: "ai uos uorking uen iu kold" },
    skills: ["grammar", "speaking"],
  },
  {
    id: "for_ago_since",
    name: "FOR / AGO / SINCE (tiempo)",
    level: "A2",
    pattern: "FOR + DURATION · AGO + TIME · SINCE + START",
    rules: ["for + duración: for two years", "ago + punto en el pasado: two years ago", "since + inicio: since 2020 (con presente perfecto)"],
    prerequisites: ["past_simple", "telling_time"],
    functions: ["talk_about_past", "interview_basics"],
    common_errors: [
      { wrong: "I work here since 2020", right: "I have worked here since 2020", why: "since usa presente perfecto" },
      { wrong: "I came here since 2020", right: "I came here two years ago", why: "Para un evento pasado concreto: ago" },
    ],
    examples: [
      { en: "I have lived here for three years.", pr: "ai jav livd jir for zri iers", es: "He vivido aquí durante tres años." },
      { en: "I moved here two years ago.", pr: "ai muvd jir tu iers ago", es: "Me mudé aquí hace dos años." },
    ],
    produce: { question_es: "Di cuánto tiempo llevas en tu ciudad.", answer_en: "I have lived here for two years.", answer_pr: "ai jav livd jir for tu iers" },
    skills: ["grammar", "speaking"],
  },
  {
    id: "quantifiers",
    name: "Cuantificadores (some, any, a lot of, much, many)",
    level: "A2",
    pattern: "SOME/ANY + NOUN · A LOT OF + NOUN",
    rules: ["some en afirmativo; any en negativo y preguntas", "a lot of para grandes cantidades (contable y no contable)", "many + contable, much + no contable (en preguntas/negativos)"],
    prerequisites: ["how_many_how_much"],
    functions: ["describe_people_objects", "handle_work_situations"],
    common_errors: [
      { wrong: "I have any money", right: "I have some money", why: "some en afirmativo" },
      { wrong: "Do you have some questions?", right: "Do you have any questions?", why: "any en preguntas" },
    ],
    examples: [
      { en: "I have some time today.", pr: "ai jav sam taim tudei", es: "Tengo algo de tiempo hoy." },
      { en: "There aren't any problems.", pr: "der arnt eni problems", es: "No hay ningún problema." },
    ],
    produce: { question_es: "Pregunta si tu tutor tiene alguna pregunta.", answer_en: "Do you have any questions?", answer_pr: "du iu jav eni kueschons" },
    skills: ["grammar", "vocabulary"],
  },
  {
    id: "telling_time",
    name: "Decir la hora (It's half past, quarter to…)",
    level: "A2",
    pattern: "IT'S + TIME",
    rules: ["It's three o'clock", "half past (y media) / quarter past (y cuarto) / quarter to (menos cuarto)", "Pregunta: What time is it?"],
    prerequisites: ["wh_to_be"],
    functions: ["handle_work_situations", "talk_about_routines"],
    common_errors: [
      { wrong: "It's fifteen for four", right: "It's quarter to four", why: "quarter to (menos cuarto)" },
      { wrong: "The time is five", right: "It's five o'clock", why: "It's + hora" },
    ],
    examples: [
      { en: "What time is it?", pr: "uat taim is it", es: "¿Qué hora es?" },
      { en: "It's half past nine.", pr: "its jaf past nain", es: "Son las nueve y media." },
    ],
    produce: { question_es: "Pregunta la hora.", answer_en: "What time is it? It's quarter to five.", answer_pr: "uat taim is it" },
    skills: ["vocabulary", "speaking"],
  },
  {
    id: "time_prepositions",
    name: "Preposiciones de tiempo (at, in, on)",
    level: "A2",
    pattern: "AT + HOUR · ON + DAY/DATE · IN + MONTH/YEAR",
    rules: ["at + hora (at 3 pm)", "on + día o fecha (on Monday)", "in + mes, año o estación (in July, in 2024)"],
    prerequisites: ["telling_time", "prepositions_basic"],
    functions: ["talk_about_routines", "interview_basics"],
    common_errors: [
      { wrong: "I work in Monday", right: "I work on Monday", why: "on + día" },
      { wrong: "The meeting is at the morning", right: "The meeting is in the morning", why: "in the morning" },
    ],
    examples: [
      { en: "I start work at 9 on Mondays.", pr: "ai start uork at nain on mandeis", es: "Empiezo a trabajar a las 9 los lunes." },
      { en: "My birthday is in October.", pr: "mai berzdei is in octouba", es: "Mi cumpleaños es en octubre." },
    ],
    produce: { question_es: "Di cuándo empiezas a trabajar (día y hora).", answer_en: "I start at 9 on weekdays.", answer_pr: "ai start at nain on uikdeis" },
    skills: ["grammar", "vocabulary"],
  },
  {
    id: "past_simple_questions",
    name: "Preguntas en pasado (did / was / were)",
    level: "A2",
    pattern: "DID + SUBJECT + BASE VERB ? · WAS/WERE + SUBJECT ?",
    rules: ["did + verbo en base: Did you go?", "was/were para preguntas con to be: Were you tired?", "Nunca: Did you went?"],
    prerequisites: ["past_simple", "past_to_be"],
    functions: ["talk_about_past", "interview_basics"],
    common_errors: [
      { wrong: "Did you went home?", right: "Did you go home?", why: "Con did el verbo va en base" },
      { wrong: "Did she was happy?", right: "Was she happy?", why: "Con to be no se usa did" },
    ],
    examples: [
      { en: "Did you enjoy the trip?", pr: "did iu enyoi de trip", es: "¿Disfrutaste el viaje?" },
      { en: "Where were you last night?", pr: "uer uer iu last nait", es: "¿Dónde estabas anoche?" },
    ],
    produce: { question_es: "Pregunta a tu tutor qué hizo el fin de semana.", answer_en: "Did you have a good weekend?", answer_pr: "did iu jav a gud uikend" },
    skills: ["grammar", "speaking"],
  },
  {
    id: "subject_object_questions",
    name: "Preguntas de sujeto y objeto (Who…?, What…?)",
    level: "A2",
    pattern: "WHO/WHAT + VERB (sujeto) · WHO/WHAT + AUX + SUBJECT (objeto)",
    rules: ["Sujeto: Who called you? (sin auxiliar)", "Objeto: Who did you call? (con did)", "What happened? (sujeto) vs What did you see? (objeto)"],
    prerequisites: ["wh_questions", "past_simple_questions"],
    functions: ["ask_basic_questions", "interview_basics"],
    common_errors: [
      { wrong: "Who did call you?", right: "Who called you?", why: "Cuando who es el sujeto no lleva did" },
      { wrong: "What you saw?", right: "What did you see?", why: "Cuando what es el objeto necesita did" },
    ],
    examples: [
      { en: "Who called you?", pr: "ju kold iu", es: "¿Quién te llamó?" },
      { en: "What did you see?", pr: "uat did iu si", es: "¿Qué viste?" },
    ],
    produce: { question_es: "Haz una pregunta de sujeto y una de objeto.", answer_en: "Who wrote this? What did you say?", answer_pr: "ju rout dis" },
    skills: ["grammar", "speaking"],
  },
  {
    id: "contrast_connectors",
    name: "Conectores de contraste (although, however, despite)",
    level: "A2",
    pattern: "ALTHOUGH + CLAUSE · HOWEVER + CLAUSE",
    rules: ["although + cláusula (aunque)", "however comienza la oración (sin embargo)", "despite + sustantivo: despite the rain"],
    prerequisites: ["linking"],
    functions: ["handle_work_situations", "interview_basics"],
    common_errors: [
      { wrong: "Although it was raining, but we went out", right: "Although it was raining, we went out", why: "No se combina although con but" },
      { wrong: "Despite of the rain", right: "Despite the rain", why: "despite + sustantivo, sin of" },
    ],
    examples: [
      { en: "Although it was late, we stayed.", pr: "ol-dou it uos leit ui steid", es: "Aunque era tarde, nos quedamos." },
      { en: "I was tired. However, I kept working.", pr: "ai uos taiad joueva ai kept uorking", es: "Estaba cansado. Sin embargo, seguí trabajando." },
    ],
    produce: { question_es: "Di algo que hiciste aunque estabas cansado.", answer_en: "Although I was tired, I finished.", answer_pr: "ol-dou ai uos taiad ai finishd" },
    skills: ["grammar", "fluency", "writing"],
  },
  {
    id: "future_will_going_to",
    name: "Futuro: WILL vs GOING TO",
    level: "A2",
    pattern: "WILL + BASE VERB · AM/IS/ARE + GOING TO + VERB",
    rules: ["will = decisión espontánea o predicción", "going to = plan o intención (con evidencia)", "Contracciones: I'll, you'll, he'll"],
    prerequisites: ["present_simple", "to_be"],
    functions: ["talk_about_routines", "interview_basics", "handle_work_situations"],
    common_errors: [
      { wrong: "I will to travel", right: "I will travel", why: "will + verbo en base, sin 'to'" },
      { wrong: "I going to work tomorrow", right: "I am going to work tomorrow", why: "Necesita am/is/are" },
    ],
    examples: [
      { en: "I'll help you.", pr: "ail jelp iu", es: "Te ayudaré." },
      { en: "We are going to move next month.", pr: "ui ar gowing tu muv next manz", es: "Nos vamos a mudar el próximo mes." },
    ],
    produce: { question_es: "Di un plan y una promesa para mañana.", answer_en: "I am going to visit my family. I'll call you.", answer_pr: "ai am gowing tu visit mai family" },
    skills: ["grammar", "speaking", "fluency"],
  },
  {
    id: "future_other",
    name: "Otras formas de futuro (be going to, present continuous)",
    level: "A2",
    pattern: "PRESENT CONTINUOUS + FUTURE TIME",
    rules: ["Presente continuo para planes fijos: I'm flying tomorrow", "going to para intenciones", "will para promesas y predicciones"],
    prerequisites: ["future_will_going_to", "present_continuous"],
    functions: ["handle_work_situations", "talk_about_routines"],
    common_errors: [
      { wrong: "I will fly tomorrow at 9 (ya es un plan fijo)", right: "I'm flying tomorrow at 9", why: "Planes fijos usan presente continuo" },
      { wrong: "I going to the gym later", right: "I'm going to the gym later", why: "Necesita am/is/are" },
    ],
    examples: [
      { en: "I'm leaving on Monday.", pr: "aim living on monday", es: "Me voy el lunes." },
      { en: "We're having a meeting at 10.", pr: "ui ar jav-ing a mit-ing at ten", es: "Tenemos una reunión a las 10." },
    ],
    produce: { question_es: "Cuenta un plan fijo que tengas.", answer_en: "I'm meeting a friend on Saturday.", answer_pr: "aim mit-ing a frend on satadei" },
    skills: ["grammar", "fluency"],
  },
  {
    id: "present_perfect",
    name: "Presente Perfecto con HAVE/HAS (experiencias)",
    level: "B1",
    pattern: "SUBJECT + HAVE/HAS + PAST PARTICIPLE",
    rules: ["Experiencias de la vida sin decir cuándo: I have visited Chile", "have para I/you/we/they; has para he/she/it", "Participios: visited (regulares), gone/seen/eaten (irregulares)", "Contracciones: I've, she's"],
    prerequisites: ["past_simple", "for_ago_since"],
    functions: ["interview_basics", "talk_about_past"],
    common_errors: [
      { wrong: "I have visited Chile last year", right: "I visited Chile last year", why: "Con momento concreto (last year) se usa pasado simple" },
      { wrong: "She have seen that movie", right: "She has seen that movie", why: "he/she/it → has" },
      { wrong: "I have went", right: "I have gone", why: "Presente perfecto usa participio, no pasado" },
    ],
    examples: [
      { en: "I have worked in three companies.", pr: "ai jav uorkt in zri companis", es: "He trabajado en tres empresas." },
      { en: "She has never been to London.", pr: "shi jas neva bin tu london", es: "Ella nunca ha estado en Londres." },
    ],
    produce: { question_es: "Cuenta dos experiencias de tu vida (sin decir cuándo).", answer_en: "I have traveled to Peru and I have lived in two cities.", answer_pr: "ai jav traveld tu peru" },
    skills: ["grammar", "speaking", "fluency"],
  },
  {
    id: "since_for",
    name: "SINCE vs FOR con presente perfecto",
    level: "B1",
    pattern: "PRESENT PERFECT + FOR + DURATION · + SINCE + START",
    rules: ["for + duración: for two years", "since + punto de inicio: since 2021", "since también: since I was a child"],
    prerequisites: ["present_perfect", "for_ago_since"],
    functions: ["interview_basics", "talk_about_routines"],
    common_errors: [
      { wrong: "I work here since 2020", right: "I have worked here since 2020", why: "Con since se usa presente perfecto" },
      { wrong: "I have lived here since three years", right: "I have lived here for three years", why: "Duración → for" },
    ],
    examples: [
      { en: "I have lived here for five years.", pr: "ai jav livd jir for faiv iers", es: "He vivido aquí por cinco años." },
      { en: "She has worked here since 2019.", pr: "shi jas uorkt jir sins tu-thousand-nineteen", es: "Ella ha trabajado aquí desde 2019." },
    ],
    produce: { question_es: "Di cuánto tiempo llevas trabajando (con for y since).", answer_en: "I have worked here for two years. Since 2023.", answer_pr: "ai jav uorkt jir for tu iers" },
    skills: ["grammar", "speaking"],
  },
  {
    id: "just_already_yet",
    name: "JUST / ALREADY / YET en presente perfecto",
    level: "B1",
    pattern: "HAVE + JUST/ALREADY + PART. · HAVEN'T + PART. + YET",
    rules: ["just = justo ahora (afirmativo)", "already = ya (afirmativo)", "yet = todavía (negativo y preguntas): Have you finished yet?"],
    prerequisites: ["present_perfect"],
    functions: ["interview_basics", "handle_work_situations"],
    common_errors: [
      { wrong: "I just finished yesterday", right: "I finished yesterday", why: "just es para algo recién hecho, no con pasado" },
      { wrong: "I haven't finished already", right: "I haven't finished yet", why: "Negativo → yet" },
    ],
    examples: [
      { en: "I have just arrived.", pr: "ai jav yast araivd", es: "Acabo de llegar." },
      { en: "Have you finished yet?", pr: "jav iu finishd yet", es: "¿Ya terminaste?" },
    ],
    produce: { question_es: "Di que acabas de terminar algo y pregunta si tu tutor ya terminó.", answer_en: "I have just finished. Have you finished yet?", answer_pr: "ai jav yast finishd" },
    skills: ["grammar", "speaking", "fluency"],
  },
  {
    id: "present_perfect_vs_past_simple",
    name: "Presente Perfecto vs Pasado Simple",
    level: "B1",
    pattern: "PAST SIMPLE + WHEN · PRESENT PERFECT + EXPERIENCE",
    rules: ["Pasado simple: momento concreto (yesterday, last year)", "Presente perfecto: experiencia sin momento", "Preguntas: Did you go? vs Have you been?"],
    prerequisites: ["present_perfect", "past_simple"],
    functions: ["interview_basics", "talk_about_past"],
    common_errors: [
      { wrong: "I have gone to the meeting yesterday", right: "I went to the meeting yesterday", why: "Con yesterday se usa pasado simple" },
      { wrong: "I never went to Japan in my life", right: "I have never been to Japan", why: "Experiencia de vida → presente perfecto" },
    ],
    examples: [
      { en: "I have never eaten sushi.", pr: "ai jav neva iten sushi", es: "Nunca he comido sushi." },
      { en: "I ate sushi last week.", pr: "ai eit sushi last uik", es: "Comí sushi la semana pasada." },
    ],
    produce: { question_es: "Di una experiencia (present perfect) y algo con momento (past simple).", answer_en: "I have visited Mexico. I went there in 2020.", answer_pr: "ai jav visited mexico" },
    skills: ["grammar", "speaking"],
  },
  {
    id: "be_able_to",
    name: "BE ABLE TO (poder) en presente perfecto",
    level: "B1",
    pattern: "HAVE/HAS BEEN ABLE TO + BASE VERB",
    rules: ["be able to = poder (todas las formas)", "En presente perfecto: have been able to", "can no tiene participio, por eso se usa be able to"],
    prerequisites: ["present_perfect", "can_ability"],
    functions: ["interview_basics", "express_needs_help"],
    common_errors: [
      { wrong: "I have can do it", right: "I have been able to do it", why: "can no se conjuga en presente perfecto" },
      { wrong: "She has been able finished", right: "She has been able to finish", why: "be able to + verbo base" },
    ],
    examples: [
      { en: "I have been able to improve my English.", pr: "ai jav bin eibol tu impruv mai inglish", es: "He podido mejorar mi inglés." },
      { en: "They have been able to finish on time.", pr: "dei jav bin eibol tu finish on taim", es: "Han podido terminar a tiempo." },
    ],
    produce: { question_es: "Di algo que has podido hacer recientemente.", answer_en: "I have been able to speak more fluently.", answer_pr: "ai jav bin eibol tu spik mor fluently" },
    skills: ["grammar", "speaking"],
  },
  {
    id: "present_perfect_continuous",
    name: "Presente Perfecto Continuo",
    level: "B1",
    pattern: "HAVE/HAS BEEN + VERB-ING",
    rules: ["Acción que empezó en el pasado y sigue: I have been working", "Enfatiza la duración de la acción", "Con how long, for, since"],
    prerequisites: ["present_perfect", "present_continuous"],
    functions: ["interview_basics", "talk_about_routines"],
    common_errors: [
      { wrong: "I am working here since 2020", right: "I have been working here since 2020", why: "Desde + duración continua → have been + ing" },
      { wrong: "I have been work all day", right: "I have been working all day", why: "have been + verbo -ing" },
    ],
    examples: [
      { en: "I have been studying English for a year.", pr: "ai jav bin studying inglish for a iar", es: "He estado estudiando inglés por un año." },
      { en: "She has been working since morning.", pr: "shi jas bin uorking sins morning", es: "Ella ha estado trabajando desde la mañana." },
    ],
    produce: { question_es: "Di qué has estado haciendo recientemente.", answer_en: "I have been preparing for an interview.", answer_pr: "ai jav bin preparing" },
    skills: ["grammar", "fluency"],
  },
  {
    id: "how_long_ppc",
    name: "HOW LONG en presente perfecto continuo",
    level: "B1",
    pattern: "HOW LONG + HAVE/HAS + SUBJECT + BEEN + VERB-ING ?",
    rules: ["how long pregunta duración", "Respuesta: for/since", "Pregunta: How long have you been working?"],
    prerequisites: ["present_perfect_continuous", "since_for"],
    functions: ["interview_basics", "ask_basic_questions"],
    common_errors: [
      { wrong: "How long you have been working?", right: "How long have you been working?", why: "have/has va antes del sujeto" },
      { wrong: "How long do you have been working?", right: "How long have you been working?", why: "No necesita do" },
    ],
    examples: [
      { en: "How long have you been learning English?", pr: "jau long jav iu bin lerning inglish", es: "¿Cuánto tiempo llevas aprendiendo inglés?" },
      { en: "I have been learning for two years.", pr: "ai jav bin lerning for tu iers", es: "Llevo dos años aprendiendo." },
    ],
    produce: { question_es: "Pregunta a tu tutor cuánto tiempo lleva trabajando en su puesto.", answer_en: "How long have you been working here?", answer_pr: "jau long jav iu bin uorking jir" },
    skills: ["grammar", "speaking"],
  },
  {
    id: "there_has_been",
    name: "THERE HAS/HASN'T BEEN + THERE HAVE BEEN",
    level: "B1",
    pattern: "THERE HAS BEEN + SINGULAR · THERE HAVE BEEN + PLURAL",
    rules: ["there has been + singular/uncountable", "there have been + plural", "Negativo: there hasn't/haven't been", "Pregunta: Has there been…?"],
    prerequisites: ["present_perfect", "there_is_are"],
    functions: ["handle_work_situations", "describe_location"],
    common_errors: [
      { wrong: "There have been a problem", right: "There has been a problem", why: "problema (singular) → has" },
      { wrong: "There has been many changes", right: "There have been many changes", why: "cambios (plural) → have" },
    ],
    examples: [
      { en: "There has been an increase in sales.", pr: "der jas bin an incris in seils", es: "Ha habido un aumento en las ventas." },
      { en: "There have been several problems.", pr: "der jav bin sevral problems", es: "Ha habido varios problemas." },
    ],
    produce: { question_es: "Di que ha habido un cambio en tu trabajo.", answer_en: "There has been a new manager this year.", answer_pr: "der jas bin a niu managa" },
    skills: ["grammar", "vocabulary"],
  },
  {
    id: "past_perfect",
    name: "Pasado Perfecto (had + participio)",
    level: "B1",
    pattern: "SUBJECT + HAD + PAST PARTICIPLE",
    rules: ["Acción anterior a otra en el pasado: When I arrived, she had left", "had para todas las personas", "Se usa con when, before, after, by the time"],
    prerequisites: ["present_perfect", "past_simple"],
    functions: ["talk_about_past", "interview_basics"],
    common_errors: [
      { wrong: "When I arrived she left already", right: "When I arrived she had left", why: "La acción más antigua lleva had" },
      { wrong: "I had saw the movie", right: "I had seen the movie", why: "Participio de see = seen" },
    ],
    examples: [
      { en: "I had finished before you arrived.", pr: "ai jav... ai had finishd bifor iu araivd", es: "Había terminado antes de que llegaras." },
      { en: "She had studied before the exam.", pr: "shi had stadid bifor de exam", es: "Ella había estudiado antes del examen." },
    ],
    produce: { question_es: "Cuenta algo que ya habías hecho antes de un evento.", answer_en: "I had eaten before the meeting started.", answer_pr: "ai had iten bifor de mit-ing" },
    skills: ["grammar", "speaking", "fluency"],
  },
  {
    id: "past_perfect_continuous",
    name: "Pasado Perfecto Continuo",
    level: "B1",
    pattern: "SUBJECT + HAD BEEN + VERB-ING",
    rules: ["Acción continua anterior a otra en el pasado: I had been working for hours", "Enfatiza duración", "Con for/since/when"],
    prerequisites: ["past_perfect", "present_perfect_continuous"],
    functions: ["talk_about_past"],
    common_errors: [
      { wrong: "I had working when you called", right: "I had been working when you called", why: "had been + verbo -ing" },
      { wrong: "I had been work for hours", right: "I had been working for hours", why: "Necesita -ing" },
    ],
    examples: [
      { en: "She had been living there for years.", pr: "shi had bin living der for iers", es: "Ella había estado viviendo allí por años." },
      { en: "We had been waiting when the bus came.", pr: "ui had bin waiting uen de bas keim", es: "Habíamos estado esperando cuando llegó el bus." },
    ],
    produce: { question_es: "Cuenta qué habías estado haciendo antes de un momento.", answer_en: "I had been studying all day before the test.", answer_pr: "ai had bin studying" },
    skills: ["grammar", "fluency"],
  },
  {
    id: "future_perfect",
    name: "Futuro Perfecto (will have + participio)",
    level: "B1",
    pattern: "SUBJECT + WILL HAVE + PAST PARTICIPLE",
    rules: ["Acción terminada antes de un momento futuro: By 2026, I will have finished", "Se usa con by, before", "Pregunta: Will you have…?"],
    prerequisites: ["future_will_going_to", "present_perfect"],
    functions: ["handle_work_situations", "talk_about_routines"],
    common_errors: [
      { wrong: "By next year I will finish my degree", right: "By next year I will have finished my degree", why: "Antes de una fecha futura → will have + participio" },
      { wrong: "I will has finished", right: "I will have finished", why: "will + have (invariable)" },
    ],
    examples: [
      { en: "By Friday, I will have finished the report.", pr: "bai fraidei ai uil jav finishd de ripot", es: "Para el viernes habré terminado el informe." },
      { en: "Will you have arrived by noon?", pr: "uil iu jav araivd bai nun", es: "¿Habrás llegado para el mediodía?" },
    ],
    produce: { question_es: "Di algo que habrás terminado para una fecha.", answer_en: "By next month I will have completed the course.", answer_pr: "bai next manz ai uil jav complited de kors" },
    skills: ["grammar", "speaking"],
  },
  {
    id: "future_perfect_continuous",
    name: "Futuro Perfecto Continuo",
    level: "B1",
    pattern: "SUBJECT + WILL HAVE BEEN + VERB-ING",
    rules: ["Duración hasta un momento futuro: By June I will have been working here for a year", "Enfatiza la duración", "Preguntas: How long will you have been…?"],
    prerequisites: ["future_perfect", "present_perfect_continuous"],
    functions: ["handle_work_situations", "talk_about_routines"],
    common_errors: [
      { wrong: "I will have worked here for 2 years by June (si la acción sigue)", right: "I will have been working here for 2 years by June", why: "Si la acción sigue, se usa continuo" },
      { wrong: "Will you have been work?", right: "Will you have been working?", why: "have been + -ing" },
    ],
    examples: [
      { en: "By 2027, I will have been working here for five years.", pr: "bai tu-thousand-twenty-seven ai uil jav bin uorking jir for faiv iers", es: "Para 2027 habré estado trabajando aquí por cinco años." },
      { en: "How long will you have been studying?", pr: "jau long uil iu jav bin studying", es: "¿Cuánto tiempo habrás estado estudiando?" },
    ],
    produce: { question_es: "Di cuánto tiempo habrás estado trabajando para una fecha.", answer_en: "By December I will have been studying for two years.", answer_pr: "bai disemba ai uil jav bin studying" },
    skills: ["grammar", "fluency"],
  },
  {
    id: "relative_clauses",
    name: "Relative Clauses: who, which, that, whose",
    level: "B2",
    pattern: "NOUN + WHO/WHICH/THAT/WHOSE + CLAUSE",
    rules: ["who → personas · which → cosas · that → ambos", "whose → posesión: the person whose car broke", "whom → personas (formal, tras preposición)"],
    prerequisites: ["subject_object_questions", "present_simple"],
    functions: ["describe_people_objects", "interview_basics"],
    common_errors: [
      { wrong: "The man which is my boss", right: "The man who is my boss", why: "who para personas" },
      { wrong: "The person whose is my friend", right: "The person who is my friend", why: "whose = posesión, no sujeto" },
    ],
    examples: [
      { en: "The woman who works here is my manager.", pr: "de wuman ju uorks jir is mai managa", es: "La mujer que trabaja aquí es mi jefa." },
      { en: "This is the project that I mentioned.", pr: "dis is de proyekt dat ai menshand", es: "Este es el proyecto que mencioné." },
    ],
    produce: { question_es: "Describe a tu jefe y un proyecto usando who y that.", answer_en: "The man who hired me is kind. The project that I led was hard.", answer_pr: "de man ju jaid mi is kaind" },
    skills: ["grammar", "vocabulary", "writing"],
  },
  {
    id: "used_to",
    name: "USED TO para hábitos del pasado",
    level: "B2",
    pattern: "SUBJECT + USED TO + BASE VERB",
    rules: ["Hábitos/estados del pasado que ya no son: I used to play football", "Negativo: didn't use to / never used to", "Pregunta: Did you use to…?"],
    prerequisites: ["past_simple"],
    functions: ["talk_about_past", "interview_basics"],
    common_errors: [
      { wrong: "I use to play when I was young", right: "I used to play when I was young", why: "Hábito pasado → used to" },
      { wrong: "I used to played football", right: "I used to play football", why: "used to + verbo base" },
    ],
    examples: [
      { en: "I used to live in the countryside.", pr: "ai ius tu liv in de kantrisaid", es: "Solía vivir en el campo." },
      { en: "Did you use to smoke?", pr: "did iu ius tu smouk", es: "¿Solías fumar?" },
    ],
    produce: { question_es: "Cuenta un hábito que tenías y ya no.", answer_en: "I used to wake up very early.", answer_pr: "ai ius tu ueik ap beri erli" },
    skills: ["grammar", "speaking", "fluency"],
  },
  {
    id: "there_used_to_be",
    name: "THERE USED TO BE (solía haber)",
    level: "B2",
    pattern: "THERE USED TO BE + NOUN (singular/plural)",
    rules: ["Solía existir: There used to be a cinema here", "Negativo: There didn't use to be…", "Diferencia con was/were: used to = solía haber antes"],
    prerequisites: ["used_to", "past_to_be"],
    functions: ["talk_about_past", "describe_location"],
    common_errors: [
      { wrong: "There was a cinema here before (implica que ya no)", right: "There used to be a cinema here", why: "used to = solía, con implicación de que ya no" },
      { wrong: "There used to was a park", right: "There used to be a park", why: "used to + be (no was/were)" },
    ],
    examples: [
      { en: "There used to be a park near my house.", pr: "der ius tu bi a park nir mai jaus", es: "Solía haber un parque cerca de mi casa." },
      { en: "There didn't use to be so much traffic.", pr: "der didnt ius tu bi sou mach trafik", es: "Antes no solía haber tanto tráfico." },
    ],
    produce: { question_es: "Di qué solía haber en tu barrio y ya no.", answer_en: "There used to be a bakery near my house.", answer_pr: "der ius tu bi a beikeri nir mai jaus" },
    skills: ["grammar", "speaking"],
  },
  {
    id: "because_as_since_for",
    name: "BECAUSE / AS / SINCE / FOR (causa)",
    level: "B2",
    pattern: "BECAUSE/AS/SINCE + CLAUSE · FOR + NOUN",
    rules: ["because = causa fuerte (más común)", "as/since = causa conocida por ambos", "for + sustantivo: for that reason"],
    prerequisites: ["linking", "why_because"],
    functions: ["handle_work_situations", "interview_basics"],
    common_errors: [
      { wrong: "I did it because of that she was late", right: "I did it because she was late", why: "because + cláusula completa" },
      { wrong: "As I was late, because I left home late (doble causa)", right: "I was late because I left home late", why: "Usa una sola causa" },
    ],
    examples: [
      { en: "I stayed home because I was tired.", pr: "ai steid jom bikaus ai uos taiad", es: "Me quedé en casa porque estaba cansado." },
      { en: "Since it's Friday, let's celebrate.", pr: "sins its fraidei lets seleb-reit", es: "Como es viernes, celebremos." },
    ],
    produce: { question_es: "Explica por qué hiciste algo con dos conectores.", answer_en: "I left early because I had a meeting. Since I was done, I went home.", answer_pr: "ai left erli bikaus ai jav a mit-ing" },
    skills: ["grammar", "writing", "fluency"],
  },
  {
    id: "classifying_questions",
    name: "Clasificar preguntas (yes/no vs wh-)",
    level: "B2",
    pattern: "YES/NO → AUX + SUBJECT · WH- → WH + AUX + SUBJECT",
    rules: ["Yes/no: Does she work? (respuesta sí/no)", "WH-: Where does she work? (información)", "Clasificar ayuda a responder con precisión"],
    prerequisites: ["wh_questions", "present_simple_aux"],
    functions: ["interview_basics", "ask_basic_questions"],
    common_errors: [
      { wrong: "Answer 'yes' to 'What do you do?'", right: "Answer with information to 'What do you do?'", why: "No es yes/no, pide información" },
      { wrong: "Do you work where?", right: "Where do you work?", why: "La palabra WH- va primero" },
    ],
    examples: [
      { en: "Are you ready?", pr: "ar iu redi", es: "¿Estás listo?" },
      { en: "When did you start this job?", pr: "uen did iu start dis yob", es: "¿Cuándo empezaste este trabajo?" },
    ],
    produce: { question_es: "Haz una pregunta yes/no y una wh-.", answer_en: "Do you like coffee? Where do you work?", answer_pr: "du iu laik kofi" },
    skills: ["grammar", "speaking", "response_time"],
  },
  {
    id: "cardinal_directions",
    name: "Puntos cardinales y direcciones",
    level: "B2",
    pattern: "NORTH/SOUTH/EAST/WEST · GO STRAIGHT / TURN LEFT",
    rules: ["Cardinales: north, south, east, west", "Indicaciones: go straight, turn left/right", "Pedir: How do I get to…?"],
    prerequisites: ["prepositions_basic", "imperative"],
    functions: ["describe_location", "handle_work_situations"],
    common_errors: [
      { wrong: "Go to the right", right: "Turn right", why: "turn right/left" },
      { wrong: "How I get to the station?", right: "How do I get to the station?", why: "Necesita auxiliar do" },
    ],
    examples: [
      { en: "Go straight and turn left.", pr: "gou streit and tern left", es: "Sigue derecho y gira a la izquierda." },
      { en: "The bank is to the north of the park.", pr: "de bank is tu de norz of de park", es: "El banco está al norte del parque." },
    ],
    produce: { question_es: "Pregunta cómo llegar a un lugar y da una indicación.", answer_en: "How do I get to the station? Go straight and turn right.", answer_pr: "jau du ai get tu de steishan" },
    skills: ["vocabulary", "speaking"],
  },
];

export const LESSON_ORDER: string[] = [
  "personal_pronouns",
  "to_be",
  "to_be_contractions",
  "possessive_basic",
  "wh_to_be",
  "why_because",
  "a_an",
  "there_is_are",
  "adjectives_qualifiers",
  "how_many_how_much",
  "this_that_these_those",
  "demonstrative_interrogative",
  "present_continuous",
  "present_simple",
  "present_simple_aux",
  "frequency_adverbs",
  "how_often",
  "prepositions_basic",
  "wh_questions",
  "can_ability",
  "adjectives_vs_adverbs",
  "intensifiers",
  "look_see_watch",
  "modal_intro",
  "should",
  "object_pronouns",
  "would_like",
  "possessive_adjectives",
  "what_vs_which",
  "could",
  "either_neither",
  "linking",
  "past_to_be",
  "past_continuous",
  "past_simple",
  "for_ago_since",
  "past_simple_questions",
  "subject_object_questions",
  "quantifiers",
  "telling_time",
  "time_prepositions",
  "contrast_connectors",
  "future_will_going_to",
  "future_other",
  "present_perfect",
  "since_for",
  "just_already_yet",
  "present_perfect_vs_past_simple",
  "be_able_to",
  "present_perfect_continuous",
  "how_long_ppc",
  "there_has_been",
  "past_perfect",
  "past_perfect_continuous",
  "future_perfect",
  "future_perfect_continuous",
  "relative_clauses",
  "used_to",
  "there_used_to_be",
  "because_as_since_for",
  "classifying_questions",
  "cardinal_directions",
];